---
- name: Soapbox Configure
  hosts: all
  gather_facts: true
  vars:
    asdf_user: pleroma
    asdf_group: pleroma

  roles:
  - role: ansible-role-asdf
    asdf_plugins:
    - name: "erlang"
      global: ["24.3.4.2"]
    - name: "elixir"
      global: ["1.13"]

  tasks:
  - name: Setup ASDF
    become: yes
    become_user: pleroma
    lineinfile:
      path: ~/.bashrc
      line: '. $HOME/.asdf/asdf.sh'

  - name: Setup ASDF completion
    become: yes
    become_user: pleroma
    lineinfile:
      path: ~/.bashrc
      line: '. $HOME/.asdf/completions/asdf.bash'
