---
- name: Soapbox Configure
  hosts: all
  gather_facts: true
  vars:
    asdf_user: pleroma
    asdf_group: pleroma

  roles:
  - role: ansible-role-asdf
    asdf_plugins:
    - name: "erlang"
      global: ["24.3.4.2"]
    - name: "elixir"
      global: ["1.13"]
