---
- name: Soapbox Configure
  hosts: all
  gather_facts: true
  vars:
    asdf_user: pleroma
    asdf_group: pleroma

  roles:
  - role: ansible-role-asdf
    asdf_plugins:
    - name: "erlang"
      global: ["24.3.4.2"]
    - name: "elixir"
      global: ["1.13"]

  tasks:
  - name: Setup ASDF
    become: yes
    become_user: pleroma
    lineinfile:
      path: ~/.bashrc
      line: '. $HOME/.asdf/asdf.sh'

  - name: Setup ASDF completion
    become: yes
    become_user: pleroma
    lineinfile:
      path: ~/.bashrc
      line: '. $HOME/.asdf/completions/asdf.bash'

  - name: Install Hex
    become: yes
    become_user: pleroma
    chdir: /opt/pleroma
    command: mix local.hex --force
    changed_when: >
      "Will always run, don't show that it changed" == 1

  - name: Install Rebar
    become: yes
    become_user: pleroma
    chdir: /opt/pleroma
    command: mix local.rebar --force
    changed_when: >
      "Will always run, don't show that it changed" == 1

  - name: Get Deps
    become: yes
    become_user: pleroma
    chdir: /opt/pleroma
    command: mix deps.get
    changed_when: >
      "Will always run, don't show that it changed" == 1

  - name: Compile Rebased
    become: yes
    become_user: pleroma
    chdir: /opt/pleroma
    command: MIX_ENV=prod mix compile
    changed_when: >
      "Will always run, don't show that it changed" == 1